spring:
    threads:
        virtual:
            enabled: true
    application:
        name: SiriAnalyzer
    datasource:
        url: jdbc:postgresql://localhost:5432/gtfsynq
        username: postgres
        password: postgres
    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
    server:
        port: 8888
    data:
        redis:
            host: localhost
            port: 6379
    kafka:
        topic: gtfs-trip-updates
        bootstrap-servers: localhost:9092
        streams:
            properties:
                auto.create.topics: "true"

gtfs:
    fetch:
        interval-ms: 30000
    feeds:
        gtfs-de:
            - https://realtime.gtfs.de/realtime-free.pb
        entur:
            - https://api.entur.io/realtime/v1/gtfs-rt/trip-updates
            - https://api.entur.io/realtime/v1/gtfs-rt/alerts
        helsinki-hsl:
            - https://realtime.hsl.fi/realtime/trip-updates/v2/hsl
        ovapi:
            - https://gtfs.ovapi.nl/nl/tripUpdates.pb
            - https://gtfs.ovapi.nl/nl/alerts.pb
        sncf:
            - https://proxy.transport.data.gouv.fr/resource/sncf-gtfs-rt-trip-updates
            - https://proxy.transport.data.gouv.fr/resource/sncf-gtfs-rt-service-alerts

management:
    metrics:
        tags:
            application: ${spring.application.name}
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
