name: SonarQube

on:
    push:
        branches: ["main"]
        paths-ignore:
            - "**/*.md"
    pull_request:
        branches: ["main"]
        paths-ignore:
            - "**/*.md"
    workflow_dispatch:

permissions:
    pull-requests: read
    contents: read

jobs:
    Analysis:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Set up JDK
              uses: actions/setup-java@v5
              with:
                  java-version: "25"
                  distribution: "temurin"

            - name: Build and Analyze with SonarQube
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  ./gradlew build
                  ./gradlew sonar
